/************
 * NAME     : JURIE.H
 * AUTOR    : Jurie Horneman, BlueByte
 * START    : 04.08.94 14:48
 * PROJECT  :
 * NOTES    :
 * SEE ALSO :
 ************/

#ifndef JURIE_H
#define JURIE_H

/*
 ** Macro definitions ******************************************************
 */

#define sgn(A) (((A)==0) ? (0) : (((A)>0) ? (1) : (-1)))

/*
#define btst(A,B) ((B) & (1<<(A)))
#define bclr(A,B) ((B) & ~(1<<(A)))
#define bset(A,B) ((B) | (1<<(A)))
#define btst(A,B) ((B) ^ (1<<(A)))
*/

/*
 ** Type definitions *******************************************************
 */

#endif

