/************
 * NAME     : CAMP.H
 * AUTOR    : Jurie Horneman, BlueByte
 * START    : 07-03-1995
 * PROJECT  : Albion
 * NOTES    :
 * SEE ALSO :
 ************/

#ifndef CAMP_H
#define CAMP_H

#include <BBDEF.H>

/*
 ** Defines ****************************************************************
 */

/*
 ** Structure definitions **************************************************
 */

/*
 ** External global variables **********************************************
 */

/*
 ** Prototypes *************************************************************
 */

void Enter_Camp(BOOLEAN Inn_flag);

#endif

