/************
 * NAME     : 3D_SELECT.H
 * AUTHOR   : Jurie Horneman, BlueByte
 * START    : 3-10-1995
 * PROJECT  : Albion
 * NOTES    :
 * SEE ALSO :
 ************/

#ifndef SELECT_3D_H
#define SELECT_3D_H

#include <BBDEF.H>

/*
 ** Defines ****************************************************************
 */

/* Action distances (3D) */
#define MAX_EXAMINE_DISTANCE		(8 * 512)
#define MAX_TALK_DISTANCE			(6 * 512)
#define MAX_MANIPULATE_DISTANCE	(4 * 512)

/*
 ** Structure definitions **************************************************
 */

/*
 ** External global variables **********************************************
 */

extern struct Module Select_M3_Mod;

/*
 ** Prototypes *************************************************************
 */

#endif

