/************
 * NAME     : MCP.H
 * AUTHOR   : Jurie Horneman, BlueByte
 * START    : 13-11-1995
 * PROJECT  : Albion
 * NOTES    :
 * SEE ALSO :
 ************/

#ifndef MCP_H
#define MCP_H

/*
 ** Defines ****************************************************************
 */

/* Game to MCP commands */
#define START_PROGRAM_MCP		(0)
#define EXIT_PROGRAM_MCP		(1)
#define SHOW_INTRO_MCP			(2)
#define SHOW_CREDITS_MCP		(3)

#endif
