//------------------------------------------------------------------------------
//File fÅr BB's Setup.exe - definition einiger verÑnderbaren Sachen:
//------------------------------------------------------------------------------

//generelles:
#define MAX_LANGUAGES 2					//0=Deutsch, 1=Englisch
#define MAX_ERROR_MESSAGES 50

//Die Auslîsung des Bildschirmes
#define RESOLUTION_X 320
#define RESOLUTION_Y 200

//MenÅfarben:
	//Der Standarthintergrund wenn kein Bild geladen ist:
	#define SETUP_DEF_BACK_LIGHT 15
	#define SETUP_DEF_BACK       7
	#define SETUP_DEF_BACK_DARK  8

#define MENU_BACK_COLOR				-1
#define MENU_BORDER_COLOR_LIGHT	-1
#define MENU_BORDER_COLOR			-1
#define MENU_BORDER_COLOR_DARK	-1

//MenÅaussehen:
#define MENU_BORDER_WIDTH			-1
