#ifndef PCLIB32_H
#define PCLIB32_H

/************
 * NAME     :  PCLIB32.H
 * AUTOR    :  BlueByte
 * PROJECT  :  Project 32
 ************/

#include <BBDEF.h>
#include <BBEXTRDF.H>
#include <BBERROR.h>
#include <BBBASMEM.h>
#include <BBOPM.h>
#include <BBEVENT.h>
#include <BBDOS.h>
#include <BBLBM.h>
#include <BBDSA.h>
#include <BBMISC.h>
#include <BBSYSTEM.h>
//#include <BBTPACK.H>
//#include <BBLBLOAD.H>

#endif

