/************
 * NAME     : MAINMENU.H
 * AUTOR    : Jurie Horneman, BlueByte
 * START    : 22-9-1995
 * PROJECT  : Albion
 * NOTES    :
 * SEE ALSO :
 ************/

#ifndef MAINMENU_H
#define MAINMENU_H

#include <BBDEF.H>

/*
 ** Defines ****************************************************************
 */

/*
 ** Structure definitions **************************************************
 */

/*
 ** External global variables **********************************************
 */

/*
 ** Prototypes *************************************************************
 */

void Enter_Main_menu(BOOLEAN First_time_flag);

#endif

