//------------------------------------------------------------------------------
//Definition der Error-defines:
//------------------------------------------------------------------------------

#define ERR_NO_VGA						1000
#define ERR_TOO_MANY_PARAMETERS  	1001
#define ERR_SCRIPT_OPEN          	1002
#define ERR_SCRIPT_READ             1003
#define ERR_OUT_OF_MEMORY           1004
#define ERR_ILLEGAL_MEM             1005
#define ERR_UNKNOWN_TOKEN           1006
#define ERR_UNKNOWN_LABEL           1007
#define ERR_BB_INIT_DSA             1008
#define ERR_LOAD_PIC                1009
#define ERR_TOKEN_NOT_IMPLEMENTED   1010
#define ERR_UNMATCHED_STRING        1011
#define ERR_NUM_PARAMETERS          1012
#define ERR_CHANGE_DRIVE            1013
#define ERR_CHANGE_DIR              1014
#define ERR_COPY_OPEN               1015
#define ERR_COPY_WRITE              1016
#define ERR_RENAME_FAILS            1017
#define ERR_CREATE                  1018
#define ERR_INT_EXPECTED            1019
#define ERR_WRONG_LANGUAGE          1020
#define ERR_ELSE_WITHOUT_IF         1021
#define ERR_ENDIF_WITHOUT_IF        1022
#define ERR_DOUBLE_ELSE             1023
#define ERR_UNMATCHED_IF            1024
#define ERR_MKDIR                   1025
#define ERR_ERRTEXT_TOO_BIG         1026
#define ERR_MENU_DO_SELECT          1027
#define ERR_MAX_MENU                1028
#define ERR_BROWSE_OPEN             1029
#define ERR_SYNTAX                  1030
#define ERR_IO                      1031
#define ERR_NO_CD                   1032
#define ERR_NO_OPTION               1033
