#ifndef BBDEFxx_H
#define BBDEFxx_H

/************
 * NAME     :  BBDEFxx.H
 * AUTOR    :  BlueByte
 * PROJECT  :  Project 32
 ************/

/* Std. */

#ifndef NULL
#define NULL 0L
#endif

#ifndef TRUE
#define TRUE 1
#endif

#ifndef FALSE
#define FALSE 0
#endif


/* Typedefs */

typedef unsigned char	UNCHAR;		/* 8 bit integer */
typedef signed char		SIBYTE;
typedef unsigned char	UNBYTE;

typedef signed short	SISHORT;	/* 16 bit integer */
typedef unsigned short	UNSHORT;

typedef signed long		SILONG;		/* 32 bit integer */
typedef unsigned long	UNLONG;

typedef SISHORT			BOOLEAN;	/* Boolean (TRUE or FALSE) */


#endif
