/************
 * NAME     : ALBION.H
 * AUTHOR   : Jurie Horneman, BlueByte
 * START    : 26-7-1995
 * PROJECT  : Albion
 * NOTES    :
 * SEE ALSO :
 ************/

#ifndef ALBION_H
#define ALBION_H

/*
 ** Defines ****************************************************************
 */

#define sgn(A) (((A)==0) ? (0) : (((A)>0) ? (1) : (-1)))

#define DIAGNOSTIC

/*
 ** Structure definitions **************************************************
 */

#endif

