//------------------------------------------------------------------------------
//Definition der Error-defines:
//------------------------------------------------------------------------------

#define ERR_NO_VGA						1000
#define ERR_TOO_MANY_PARAMETERS  	1001
#define ERR_SCRIPT_OPEN          	1002
#define ERR_SCRIPT_INFO          	1003
#define ERR_SCRIPT_READ          	1004
#define ERR_OUT_OF_MEMORY        	1005
#define ERR_ILLEGAL_MEM          	1006
#define ERR_UNKNOWN_TOKEN        	1007
#define ERR_UNKNOWN_LABEL        	1008
#define ERR_BB_INIT_DSA          	1009
#define ERR_LOAD_PIC             	1010
#define ERR_TOKEN_NOT_IMPLEMENTED   1011
#define ERR_UNMATCHED_STRING        1012
#define ERR_NUM_PARAMETERS          1013
#define ERR_CHANGE_DRIVE            1014
#define ERR_CHANGE_DIR              1015
#define ERR_COPY_OPEN               1016
#define ERR_COPY_WRITE              1017
#define ERR_RENAME_FAILS            1018
#define ERR_CREATE                  1019
#define ERR_INT_EXPECTED            1020
#define ERR_WRONG_LANGUAGE          1021
#define ERR_ELSE_WITHOUT_IF         1022
#define ERR_ENDIF_WITHOUT_IF        1023
#define ERR_DOUBLE_ELSE             1024
#define ERR_UNMATCHED_IF            1025
#define ERR_MKDIR                   1026
#define ERR_ERRTEXT_TOO_BIG         1027
#define ERR_MENU_DO_SELECT          1028
#define ERR_MAX_MENU                1029
#define ERR_BROWSE_OPEN             1030
#define ERR_SYNTAX                  1031
#define ERR_IO                      1032
